version: '3'

services:
  app:
    image: ambientum/php:7.4-nginx
    container_name: ceos_app
    restart: always
    volumes:
      - .:/var/www/app
    env_file:
      - .env
    ports:
      - "${DOCKER_HTTP_PORT}:8080"
      - "${DOCKER_HTTPS_PORT}:443"
    depends_on:
      - db
    networks:
      - ceos_network

  db:
    image: mysql:5.7
    container_name: ceos_db
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "${DOCKER_DB_PORT}:3306"
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    networks:
      - ceos_network

volumes:
  dbdata:

networks:
  ceos_network:
    driver: bridge
